name: Build

on: [push, pull_request]

jobs:
  build-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build
        shell: cmd
        run: |
          For /R %%l in (*.sln) do (
            dotnet build %%l
          )
